language: ruby

rvm:
  - 2.4.2

services:
  - postgresql
  
before_install:
  - gem install bundler
  - gem install rails -v 5.1.4

before_script:
  - export PARALLEL_TEST_PROCESSORS=4
  - bundle install
  - rails db:setup

script:
  - rspec
  - cucumber