language: ruby

rvm:
  - 2.4.2

services:
  - postgresql
  
before_install:
  - gem install bundler
  - gem install rails -v 5.1.4
  
cache:
  bundler: true
  directories:
    - vendor/bundle

install:
  - bundle install --deployment

before_script:
  - export PARALLEL_TEST_PROCESSORS=4
  - rails db:setup
  - rspec
  - cucumber