language: ruby

rvm:
  - 2.4.2

services:
  - postgresql
  
before_install: gem install bundler

before_script:
  - export PARALLEL_TEST_PROCESSORS=4
  - rails db:setup

script:
  - rspec
  - cucumber