language: ruby
rvm:
 - 2.4.2
services:
  - postgresql
script:
  - gem install bundler
  - bundle install
  - export RAILS_ENV=test
  - bundle exec rake db:schema:load
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec
  - bundle exec cucumber