language: ruby

rvm:
  - 2.4.2

services:
  - postgresql
  
before_install: gem install bundler

before_script:
  - "sh -e /etc/init.d/xvfb start"
  - cp config/database.travis.yml config/database.yml
  - export PARALLEL_TEST_PROCESSORS=4
  - RAILS_ENV=development bundle exec rake db:create db:migrate

script:
  - bundle exec rspec
  - bundle exec cucumber